// <auto-generated />
namespace QuanLyKaraoke.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:QuanLyKaraoke/QuanLyKaraoke/Migrations/202011160546293_initial.Designer.cs
            get { return "202011160546293_initial"; }
=======
            get { return "202011160722097_init"; }
>>>>>>> Cong_branch:QuanLyKaraoke/QuanLyKaraoke/Migrations/202011160722097_init.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
